googleinterns/step272-2020

package-lock.json
portfolio/frontend/src/containers/SGonksPlatform/MySGonks/MySGonks.js
portfolio/frontend/src/containers/SGonksPlatform/MySGonks/MySGonks.module.css

* All content is dummy data
* Chart is a placeholder png
* Button is working

MysGonks page prototype

---

makefile
portfolio/frontend/src/App.js
portfolio/frontend/src/containers/Login/Login.js
portfolio/frontend/src/containers/Login/Login.module.css
portfolio/frontend/src/containers/SGonksPlatform/Dashboard/Dashboard.js
portfolio/frontend/src/containers/SGonksPlatform/Dashboard/Dashboard.module.css
portfolio/frontend/src/containers/SGonksPlatform/MySGonks/MySGonks.js
portfolio/frontend/src/containers/SGonksPlatform/SGonksPlatform.js

* App now routes properly between login and the sgonks platform 
* Dashboard's buttons are now working 
* Made styling amends to buttons since styling was broken when button was replaced with Link tag

Prototype routing

---

.gitignore
project/frontend/package.json
project/frontend/src/App.js
project/frontend/src/services/firebase.js

* Auth flow now working properly with firebase auth 
* **TO RUN THIS AFTER PULLING PLEASE DO:**
* Get the config/firebaseConfig.js file from mercurylin@ and paste this into the services/ directory
* Make sure that this file is gitignored (should already be after pulling)
* User ID is queried from backend by passing in email after user is logged in 
* User ID is later used to query the database for the user's other information
* No backend support for querying for ID using email as of yet, so **ID is currently hardcoded to 123**

Set up firebase authentication

---

project/pom.xml
project/scripts/dates.py
project/scripts/fetch_trends.py
project/scripts/main.py
project/src/main/java/com/google/sps/servlets/TestServlet.java
project/src/main/webapp/WEB-INF/appengine-web.xml

- Add datastore dependencies to maven
- Weird project ID workaround in appengine-web.xml
- Python script now both retrieves and updates trends data from datastore when main.py is run
- Add code to demonstrate retrieval of trends data from datastore in TestServlet.java file

Integrate Datastore into project backend

---

project/frontend/babel.config.js
project/frontend/jest.config.js
project/frontend/jest.config.json
project/frontend/package.json
project/frontend/src/App.js
project/frontend/src/App.test.js
project/frontend/src/components/HeaderBar/HeaderBar.test.js
project/frontend/src/index.js
project/frontend/test/jest/__mocks__/fileMock.js
project/frontend/test/jest/__mocks__/styleMock.js
project/frontend/webpack.config.js

* Uses Jest and Enzyme for testing 
* Need to run `npm i` in frontend folder after pulling to install new dependencies 
* Currently no comprehensive testing, just setup 
More tests to come in later PR.

Configure frontend testing setup 

---

project/src/main/java/com/google/sps/data/Investment.java
project/src/main/java/com/google/sps/servlets/InvestmentServlet.java

Add a data points argument as an immutable list to the Investment object constructor because auto value class required all data to be in immutable types. 
Use "ImmutableList.copyOf( --- a list ---- )" function to create an immutable list

Add immutable list for data points in Investment constructor.

---

.gitignore
project/src/main/java/com/google/sps/data/CompetitorInfo.java
project/src/main/java/com/google/sps/data/User.java
project/src/main/java/com/google/sps/data/UserCompetition.java
project/src/main/java/com/google/sps/database/ConnectionPoolContextListener.java
project/src/main/java/com/google/sps/servlets/CompetitionInfoServlet.java
project/src/main/java/com/google/sps/servlets/InvestmentServlet.java
project/src/main/webapp/WEB-INF/logging.properties

- add additional columns to cloud sql db for participant rank, rank yesterday, competition name etc
- update hard coded database entries to match db updates
- minor changes to gitignore and logging file
- update servlets to read in new information from database
- change all instances of 'ldap' to 'email' at backend
- some minor changes to variable types and naming

Update servlets and database to include additional information not coded last time

---

project/scripts/fetch_trends.py
project/scripts/main.py
project/src/main/java/com/google/sps/servlets/TrendingServlet.java

- update python script to fetch trending data and update datastore
- update trending servlet to read this data from datastore and return in an array

Add functionality for returning global trends

---

project/frontend/src/containers/Explanation/Explanation.js
project/frontend/src/containers/Explanation/Explanation.module.css

Added the actual explanation about sGonks project and how to play the game. Please let me know if you think I'm missing something.
This is how the page looks like.

Implemented the explanation page as designed.

---

project/src/main/java/com/google/sps/data/Investment.java
project/src/main/java/com/google/sps/database/ConnectionPoolContextListener.java
project/src/main/java/com/google/sps/servlets/InvestmentCalculator.java
project/src/main/java/com/google/sps/servlets/InvestmentServlet.java

- Adjust investment object to also include the investment's current value
- Add functionality to investment servlet to return an array of datapoints for each investment
- Minor adjustment to InvestmentCalculator to make date function more general
- Minor adjustment to data in database just so I have fewer datapoints to look at for now
This has been branched off the rankings branch, please confirm needed changes to PR #69 first. Once both branches are approved I'll merge this over and then merge rankings into master.

Final changes needed to supply all data to frontend for now

---

project/frontend/src/containers/Explanation/Explanation.js
project/frontend/src/containers/Explanation/Explanation.module.css

- Back Button now redirected back to the dash board.
- Decrease font size for the header

Implement the back button to redirect to the dashboard.

---

project/frontend/src/services/firebase.js
project/pom.xml
project/src/main/java/com/google/sps/database/FirebaseContextListener.java
project/src/main/java/com/google/sps/servlets/AuthServlet.java

- As soon as the user signed in the token is passed to verified at the backend by POST function
- The AuthServlet decoded and verified the idToken and saved it in the session if successful.
- When the user logged out the idToken that's been saved in the session is removed.
- Initialised and set up Firebase for ID verification in FirebaseContextListener.java

The token is successfully verified  when user logged in.  

---

project/src/main/java/com/google/sps/servlets/AuthServlet.java
project/src/main/java/com/google/sps/servlets/CompetitionsServlet.java
project/src/main/java/com/google/sps/servlets/CompetitorsServlet.java
project/src/main/java/com/google/sps/servlets/InvestmentServlet.java
project/src/main/java/com/google/sps/servlets/SingleCompetitionServlet.java

- authentication now creates new user in database when given unfamiliar login details
- all relevant servlets now return a 400 bad request error when supplied with not integer ids for users or competitions
Resolves #92, Resolves #75

Fix two small backend issues - add new user on auth, return 400 on invalid id parameter

---

project/frontend/src/components/UI/LinkButton/LinkButton.js
project/frontend/src/containers/CreateCompetition/CreateCompetition.js
project/frontend/src/containers/CreateCompetition/CreateCompetition.module.css

Implemented the UI for the Create Competition Page.
For now adding the participants user has to type out an email in the text box and click the add button.
This is how the page looks 
The plan is to displayed the entered email when the add button is clicked.

Implement the UI for the Create Competition page.

---

project/scripts/fetch_trends.py

Accidentally merged a small bug, just fixing a 1 that should have been a negative 1

Fix missing negative sign bug

---

project/frontend/src/App.js
project/frontend/src/components/RecentBuys/RecentBuysList.js
project/frontend/src/components/UI/Button/Button.js
project/frontend/src/components/UI/Button/Button.module.css
project/frontend/src/components/UI/LinkButton/LinkButton.module.css
project/frontend/src/containers/Marketplace/Marketplace.js
project/frontend/src/containers/Marketplace/Marketplace.module.css

* Marketplace UI
* Half of the page is already linked with logic (particularly the right column) 
* Left side is UI only atm
* Decision made to have search button in place so that the chart data is queried when and only when user clicks search, instead of doing live queries (with every keystroke) - this is due to each query taking ~5 seconds which would make live querying infeasible
* Factored out a Button component - which is just a simple button with styling
Loooks liket his

Implement marketplace UI

---

project/frontend/package.json
project/frontend/src/components/ParticipantCard/ParticipantCard.js
project/frontend/src/components/ParticipantCard/ParticipantCard.module.css
project/frontend/src/containers/CreateCompetition/CreateCompetition.js
project/frontend/src/containers/CreateCompetition/CreateCompetition.module.css

Use Participants Card component to displayed each participants emails that's been added by the user.
Participants Card component has a delete icon for user to remove the participants from the list.

Implemented the add and removed participants from the list.

---

project/src/main/java/com/google/sps/data/NetWorth.java
project/src/main/java/com/google/sps/servlets/ContextDataServlet.java
project/src/main/java/com/google/sps/servlets/InvestmentCalculator.java
project/src/main/java/com/google/sps/servlets/NetWorthHistoryServlet.java
project/src/main/java/com/google/sps/servlets/ScheduledServlet.java

- update the scheduled servlet to add the user's net worth to the datastore indexed by current date when run
- added a servlet for returning the networths of every competitor in a given competition
- added a networth object for the purposes of packaging the JSON return of the networth servlet
- some minor bug fixes due to type inconsistencies
Resolves #117, Resolves #112

Implement functionality for maintaining competitor networth history

---

project/src/main/java/com/google/sps/servlets/ContextDataServlet.java
project/src/main/java/com/google/sps/servlets/InvestmentCalculator.java
project/src/main/java/com/google/sps/servlets/InvestmentServlet.java
project/src/main/java/com/google/sps/servlets/NewInvestmentServlet.java

- minor bug fixes in the invesment calculator
- add new servlet that either retrieves existing data from datastore and returns as array, or runs Cloud Function to fetch this data first.
Resolves #114

Add servlet for fetching contextual data on a new search term

---

project/scripts/data_generator.py

I forgot I was summing the data over 24 hours to determine each day's data point, so I have amended the gaussian random number generator to use probabilities that reflect this.

Fix range to work over 24 hours worth of datapoints

---

project/frontend/src/App.js
project/frontend/src/components/CompetitionCard/CompetitionCard.js
project/frontend/src/components/ErrorMessage/ErrorMessage.js
project/frontend/src/components/ErrorMessage/ErrorMessage.module.css
project/frontend/src/components/HeaderBar/HeaderBar.js
project/frontend/src/components/RecentBuys/RecentBuysList.js
project/frontend/src/components/RecentBuys/RecentBuysList.module.css
project/frontend/src/components/SGonksLists/LongSGonksList/LongSGonksList.js
project/frontend/src/components/SGonksLists/ShortSGonksList/ShortSGonksList.js
project/frontend/src/components/SGonksLists/ShortSGonksList/ShortSGonksList.module.css
project/frontend/src/components/TrendingSearches/TrendingSearches.js
project/frontend/src/containers/SelectCompetition/SelectCompetition.js
project/frontend/src/hoc/PageRouter/PageRouter.js

This PR makes it so that if one servlet fails the whole app doesn't work. The areas where that servlet's data is used displays an error. 
* Created component ErrorMessage. This is a super simple component where it displays "Failed to load x" where x is the child prop passed in. Used in...
* Recent buys 
* Long sgonks list
* Short sgonks list 
* Trending searches
* Also edited SelectCompetition so that if the competitionsList doesn't return properly, it shows an error message instead of going bork
* Also fixed a bug where select competition was throwing an error because a method name change that happened in a previous PR

Partial data displays on frontend 

---

project/frontend/src/App.js
project/frontend/src/components/RankingsList/RankingsListRow/RankingsListRow.js
project/frontend/src/containers/Competition/Competition.js
project/frontend/src/hoc/PageRouter/PageRouter.js

- Add fetch functions to app.js to get rankings and networth history data.
- Return this data to the competition container in the page router
- Format data for chart display
- Replace placeholder data with servlet returned data on all cards
No layout changes made.
Resolves #54

Add servlet returned data to competition page

---

project/frontend/src/components/RankingsList/RankingsList.js

This is a 4 line PR.. all the other lines are just my formatter

Add error message for data load failure to comp page

---

project/frontend/src/containers/Competition/Competition.js
project/frontend/src/containers/Marketplace/Marketplace.js
project/frontend/src/containers/Marketplace/Marketplace.module.css

* Fetches contextData on onClick of "Search" button 
* Asynchronous function 
* fetches and averages chart data (data/24) 
* formats data to be chart compatible (separate function: formatChatData)
Chart block display functionalities:
* Unsearched state displays search prompt
* Loading displayed if fetching or marshalling data
* Fetched normally
* If contextData returns no results (i.e. if you search a very obscure term, trends has no data)

Marketplace logic part 1 (fetching contextData and loading chart)

---

project/frontend/src/containers/CreateCompetition/CreateCompetition.js
project/frontend/src/containers/CreateCompetition/CreateCompetition.module.css

On the Create Competition page, check if the dates that the user choose is valid or not.
- Start date has to be today or after today
- end date has to be after start date
Displayed a message on the screen if the chosen date is invalid.
I was planning to do a popup displaying the message but I'm taking too long to get it to work so I'm planning to come back and improve it at the end if I have time.
This is how the message is displaying for now.

Check if the date that users input is valid or not on the Create competition page.

---

project/frontend/src/components/InvestmentChart/InvestmentChart.js
project/frontend/src/containers/Dashboard/Dashboard.js
project/frontend/src/hoc/PageRouter/PageRouter.js

- Add remaining logic for dashboard:
- - retrieving and displaying user name
- - Populating chart with real investment data
- - Linking buttons
Resolves #147 
Based off competition-page-logic as it relies on the InvestmentChart component

Dashboard logic

---

project/src/main/java/com/google/sps/servlets/BuyServlet.java

Removed some stupid code that somehow ended up in master - was updating networth on an investment purchase.
Added a sanity check for whether the user had enough trend bucks available to make the purchase.

Remove code updating networth in buy servlet

---

project/frontend/src/containers/CreateCompetition/CreateCompetition.js
project/frontend/src/containers/CreateCompetition/CreateCompetition.module.css

- Display an error message while creating a competition in an alert pop up instead of text.
- Add a pop up to confirm that the competition is created
Example:

Use pop up to display error message instead of text.

---

project/frontend/src/components/InvestmentChart/InvestmentChart.js
project/frontend/src/containers/MySGonks/MySGonks.js

* This makes is so that if investment servlet isn't working, the frontend app doesn't just complain about it and stop working. 
* Now displays an error message for the singular components

Error handling in MySGOnks and InvestmentChart components

---

project/frontend/src/App.js
project/frontend/src/components/CompetitionCard/CompetitionCard.js
project/frontend/src/containers/MySGonks/MySGonks.js

* Replace all ???s with initial worth (500) when approrpaite
* This is a constant in App.js, exported and imported where needed (as is with compId)

Update initial worth variable

---

project/frontend/src/App.js
project/frontend/src/components/ChartCard/ChartCard.js
project/frontend/src/components/ChartCard/ChartCard.module.css
project/frontend/src/components/CompetitionCard/CompetitionCard.js
project/frontend/src/components/InvestmentChart/InvestmentChart.js
project/frontend/src/containers/MySGonks/MySGonks.js
project/frontend/src/containers/MySGonks/MySGonks.module.css

* charts are now not being shy and filling up the whole space they're given

Fix chart display

---

project/frontend/src/components/RankingsList/RankingsListRow/RankingsListRow.js
project/frontend/src/components/RankingsList/RankingsListRow/RankingsListRow.module.css
project/frontend/src/components/RankingsList/RankingsListTitleRow/RankingsListTitleRow.js
project/frontend/src/components/RankingsList/RankingsListTitleRow/RankingsListTitleRow.module.css

* Just styling change 
* Made diff indicator have its own cell
* Everything else is formatter wars

Amend diff indicator display on competition page (rank list)

---

project/frontend/package.json
project/frontend/src/components/UI/LoginButtonSet/LoginButtonSet.js
project/frontend/src/containers/CreateCompetition/CreateCompetition.js
project/frontend/src/containers/SelectCompetition/SelectCompetition.js
project/frontend/src/hoc/PageRouter/PageRouter.js
project/src/main/java/com/google/sps/servlets/CompetitionsServlet.java
project/src/main/java/com/google/sps/servlets/CreateCompetitionServlet.java

Add routing:
- From the Select Competition page --> Create Competition page
- From Create Competition page 
- Cancel --> Back to select competition page
- Confirm --> to the dash board for that competition
To redirect to the dash board of the new Competition that's just been created, this requires a competition id from the database. Before the data from create competition was received and put in database in the CompetitionsServlet which is sending all the competitions in database to frontend. We think that it will be better to have one Servlet just to focus on request/response with the Create competition page.  doPOST is move from the Competitions Servlet and to a new servlet called  Create Competition servlets that received the information from the create competition page and put it in …

Routing to create competition page and explanation page.

---

project/functions/main.py

- updated all the files in the cloud function, which also meant slightly modifying the entry point to be compatible with the edits. This is the new entry point.

Update entry point for cloud function data fetch

---

project/frontend/src/components/SGonksLists/LongSGonksList/LongSGonkRow/LongSGonkRow.js
project/frontend/src/components/SGonksLists/LongSGonksList/LongSGonksList.js
project/frontend/src/containers/MySGonks/MySGonks.js
project/frontend/src/hoc/PageRouter/PageRouter.js

* This finishes off the selling logic on mySgonks page. 
* When the sgonk is successfully sold, relevant servlets are recalled (particularly, general info and investments data) and frontend display is updated accordingly

Update relevant data when sgonk is sold successfully

---

project/frontend/src/containers/LandingPage/LandingPage.js
project/frontend/src/containers/LandingPage/LandingPage.module.css

* Updated the description and
* Fixed some styling

Update hero 

---

project/src/main/java/com/google/sps/servlets/BuyServlet.java

- Fixed bug where participant id was checked instead of the user paramater
- Fixed bug where generated keys code had been pasted into the wrong section
- Added some better logging of potential errors

2 bug fixes in buy servlet, and added better logging of errors
